### ISSUE TITLE
Facing issue in ajax call

### ISSUE THREAD

**Issue by sumeetclabs** [floatschedule/api#10]
Hi All,

I am trying to call api from the ajax call. But it shows error while executing.
My Code:-
 $.ajax({
                        url: 'https://api.floatschedule.com/api/v1/tasks',
                        type: 'GET',
                        beforeSend: function (xhr) {
                            xhr.setRequestHeader('Authorization', 'Bearer --bearer id--');
                        },
                        data: {},
                        success: function (response) { console.log(response);},
                        error: function (error) { console.log(error);},
                        }); });
 
Can you please correct me if i wrong somewhere?

Thanks
Sumeet

**Comment by e2718281828** [comment]
Hello,

I am facing  similar problem as summetclabs: I am trying to get the JSON files from 

https://api.floatschedule.com/api/v1/people

Here is how the request is made:
var xhr = new XMLHttpRequest();
var url = 'https://api.floatschedule.com/api/v1/people';
xhr.open('GET', url, true);
xhr.setRequestHeader("Authorization", 'Bearer --bearer id--');
xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
xhr.setRequestHeader("Accept","application/json");
 
// Response handlers.
  xhr.onload = function() {
    var text = xhr.responseText;
    console.log(text);
  };

xhr.send();

However, from the debugger of the browser (firefox), I see that actually the request is not successful (401 error code):
![screenshot](https://cloud.githubusercontent.com/assets/5225723/6736901/d9a5fbe0-ce35-11e4-98a8-40959c63689f.jpg)
Here is the output from Console:
![screen shot 2015-03-19 at 12 47 52 pm](https://cloud.githubusercontent.com/assets/5225723/6736952/398b3b42-ce36-11e4-9169-baf7109b3a00.png)

If I use the plugin Rest Easy (https://addons.mozilla.org/en-us/firefox/addon/rest-easy/), then I can access the JSON data with no problem.

Do you have any suggestion on what's happening? 

Sincerely,
e2718281828

**Comment by lgelfan** [comment]
Not reproducible with valid data, if you are still having trouble, please double-check your data and let us know.
