### ISSUE TITLE
Why are tasks grouped the way they are?

### ISSUE THREAD

**Issue by spilliams** [floatschedule/api#13]
Hello,
I'm starting to dive in on your API because my team wants a middleman to keep our Float and [Harvest](https://www.getharvest.com/) accounts on the same page.
I'm curious about the /tasks endpoint. Specifically, why are tasks grouped the way they are?
-Spencer

**Comment by lgelfan** [comment]
Tasks in this version of the API are grouped in that way mostly to populate our UI. We are working on a new version of the API that will be less UI-focused.
