### ISSUE TITLE
Time?

### ISSUE THREAD

**Issue by matthewfowles** [floatschedule/api#14]
Hi 

I need the Api to get time work on a task on a specific day or between two date and the same for all tasks between two dates. Is there any ideas to make this possible?

**Comment by lgelfan** [comment]
You can generally pass a start and end value like: `start_day=20160101&end_day=20160127` to restrict values with date fields. Values with multiple days may require additional filtering on your side. You should then be able to add up the time. You can also look into the CSV output for reports if that is close to what you need. Thanks.
