### ISSUE TITLE
Person creation with skills and level

### ISSUE THREAD

**Issue by Dr-Jerm** [floatschedule/api#15]
I would like to utilize the skills 1,2,3 in when creating a person, however I do not currently a way to do this in the current API. How would you suggest I go about adding skills to a person and choosing a specific level for that skill?

**Comment by Dr-Jerm** [comment]
Some context. I am working with my company to transition our employee records into Float.

Is there a way to set the access_rights/access_id so that a person can be created as a member so they get the "set your password "email?

**Comment by lgelfan** [comment]
You can use a json string with skill-value combination for the "skills" value, see the skills *value* example response in the API docs, e.g., `skills='[
        {
            "name": "css",
            "level": 3
        },
        {
            "name": "Flash",
            "level": 2
        }
    ]'`
