### ISSUE TITLE
Chained filters aren't working or are not a feature

### ISSUE THREAD

**Issue by varun-d** [floatschedule/api#16]
### Challenge

Get task for one "people_id" for one particular day, at the minimum, get tasks for one "people_id" for "today".

### Code

```
https://api.floatschedule.com/api/v1/tasks?people_id=<redacted>&start_day=2015-11-07
```
*Tested:* 5 times with different start dates and different people_id with different tasks.

### Result

I still see results from 2015-11-05. Are chained filters implemented in the API?

### Temp Workaround

I can get all tasks for the person and filter it myself. (Using Python for my project)

**Comment by lgelfan** [comment]
Not sure exactly what you mean by chained filters in this context (REST API). It does support multiple filter arguments. The current API will fetch tasks by week as it was designed to service the Float UI. Future versions of the API will have the ability to query by pure data values but that is not supported for start_day on tasks right now.
