### ISSUE TITLE
Tags vs. Skills?

### ISSUE THREAD

**Issue by batemapf** [floatschedule/api#17]
It looks like the /people/ endpoint is set up to publish `skills:` information. however, there is no corresponding field in the user-facing UX, only `Tags:` (and conversely, the /people/ endpoint does not publish 'Tags:` information).  Am I missing something?

**Comment by lgelfan** [comment]
Hi Patrick,

Skills was the original name for people tags as you can assign a "skill level" to a tag for a person (where you can not for a project). We found different companies were using these attributes for things other than skills, hence the UI name change. The API docs still refer to them as skills for people as that is the data value. Sometimes the data value and the UI value/label differ. We try to hide as much of that as possible, but sometimes it does surface. We didn't want to change the value in an existing API as some clients may already have had skills in their code.

Sorry for any confusion. Let us know if there is anything else we can help you with.
