### ISSUE TITLE
Assign Project Managers to a a project via the API

### ISSUE THREAD

**Issue by chris-sinclair** [floatschedule/api#19]
Hi, Not sure this is really an issue, but is it possible to assign Project Managers to a project via the API? I couldn't find an example, and have had a go buy attempting to update a project with a PM userid in an array, but no luck.
Thanks,

Chris

**Comment by ecraver** [comment]
I tried the same thing with no luck. This would help our organization out a lot. Thanks, Eric

**Comment by ecraver** [comment]
I haven't got this to work with PUT request. But on POST I set the project.creator_id = people.access_id; which intern sets that person as project manager.

**Comment by lgelfan** [comment]
You can use `project_manager_id` for create and update on the **projects** endpoint. Note that the array in the list output is a convenience to avoid a look-up. @ecraver yes, you can also use `creator_id` which was the original key name (project_manager_id is an alias for creator_id) and the value is people.access_id which is the same as account_id (someone who has access to log in to the account, the list you can see on the "/admin/adminsList" Account Settings page). 

Note that we are working a the next version of the API which will be more abstracted from the UI logic the v1 API was based on. Thanks for using Float, if you have any other questions, please open another ticket here or contact us at: support@float.com
