### ISSUE TITLE
Add the project_id as the task API parameter

### ISSUE THREAD

**Issue by nicolasbraun** [floatschedule/api#20]
Hi Guys,

Looking at the structure of the response I understand why the `people_id` is an available parameter and not the `project_id`but are there any plans to add this ?

We are trying to build a tool that compares the time a user has passed on a project VS the planned one and have to fetch the whole task of the user, with desastrous performance.

Best,

Nicolas

**Comment by lgelfan** [comment]
Hi Nicolas,

We are working on a new version of the API that will be a bit more consistent in data format and filtering.

For the v1 task endpoint, you should be able to use `/tasks?filter[project_id]=97` format for project_id filter. Hopefully that should work for you in this case.

**Comment by nicolasbraun** [comment]
Thanks a lot !
