### ISSUE TITLE
Limit increase

### ISSUE THREAD

**Issue by jamesryanbell** [floatschedule/api#26]
Hi

I am trying some bulk actions via the API e.g. adding a client using: https://api.float.com/api/v1/clients but instead of receiving a 429 at 400 I am receiving it at around 100 requests.

Can you increase my limit if I provide you with my key over email etc.?

Thanks,
James

**Comment by lgelfan** [comment]
Hi James,

We recently updated the limits to increase GET requests to 400/minute and 20/second and to balance that reduced writes (POST, PUT, etc.) to 100/minute and 10/second. Realize this could cause confusion so we've made all requests 400/minute limit but kept the 10/second lower limit for non-GET. Hopefully your application can accommodate that. We'll update the documentation accordingly. Let me know if that presents any issues. 

Our goal is to use reasonable limits to provide the best experience for everyone and we periodically review the limits to make sure this is the case.
