### ISSUE TITLE
Holiday Endpoint

### ISSUE THREAD

**Issue by batemapf** [floatschedule/api#27]
The holiday endpoint appears to only return holidays in the current calendar year and in the future. For example, this was returned a few minutes ago:
```
{'holidays': [{'date_doy': '361', 'date': '2016-12-26', 'holiday_name': 'Christmas', 'holiday_id': '18822', 'end_date': '2016-12-26'}], 'status': 200}
```

Is there a param that may be used to select a point or range in time from which holidays may be fetched?

**Comment by glennrogers** [comment]
Hey @batemapf 

Like the Tasks, you can specify the start day and the number of week's you'd like to return, e.g.

?start_day=2016-01-01&weeks=52

Would return all the holidays through this year. I hope that helps.

Cheers,

Glenn
